WITH GRADES AS (

SELECT
EMPLID,
CLASS_TERM AS TERM_CODE,
CTERM_TERM_LDESC AS CLASS_TERM,
CLASS_SESSION_CODE AS SESSION_CODE,
STUDENT_ACAD_CAREER EOT_ACAD_CAREER,
STUDENT_ACAD_PROG_PRIMARY_CODE AS EOT_PROGRAM_CD,
STUDENT_ACAD_PROG_PRIM_LDESC AS EOT_PROGRAM,
STUDENT_COLLEGE_CODE AS EOT_COLLEGE_CD,
STUDENT_COLLEGE AS EOT_COLLEGE,
STUDENT_DEPT_CODE AS EOT_DEPARTMENT_CD,
STUDENT_DEPT AS EOT_DEPARTMENT,
STUDENT_ACAD_PLAN_CODE AS EOT_ACAD_PLAN_CD,
STUDENT_ACAD_PLAN AS EOT_ACAD_PLAN,
CLASS_COLLEGE_CODE,
CLASS_COLLEGE,
CLASS_DEPT_CODE,
CLASS_DEPT,
CLASS_PREFIX,
CLASS_PREFIX_LONGDESC,
CLASS_CATALOG_NBR,
CLASS_SECTION,
CLASS_DESCR,
CASE WHEN CLASS_DEPT_CODE IN ('PHYS','MATH','BIOL','CHEM') THEN 1 ELSE 0 END AS BCMP,
CASE WHEN CLASS_DEPT_CODE IN ('PHYS','MATH','BIOL','CHEM') THEN ENRL_UNITS_TAKEN ELSE 0 END AS BCMP_UNITS_TAKEN,
ONLINE_COURSE,
ENRL_UNITS_TAKEN AS UNITS_TAKEN,
ENRL_GRADING_BASIS  AS GRADING_BASIS,
ENRL_OFFICIAL_GRADE AS OFFICIAL_GRADE,
ENRL_EARNED_CREDIT AS EARNED_CREDIT,
ENRL_UNITS_ATTEMPTED AS UNITS_ATTEMPTED,
ENRL_GRADE_POINTS AS GRADE_POINTS,
ENRL_STATUS_CD AS STATUS_CD,
CLASS_GE_FLAG AS GE_FLAG,
CLASS_DIVISION AS DIVISION,
GPA_FLAG,
CLASS_INSTRUCTION_MODE,
CLASS_INSTRUCTOR_EMPLID,
PERS_HOME_POSTAL AS HOME_ZIP_CD

FROM       IRAMASTER.GRADES_C
WHERE STUDENT_ACAD_CAREER_CODE = 'UGRD'

),

COHORT AS (

SELECT DAE_EMPLID, DAE_CHT_TERM
FROM IRAMASTER.SSD_DAE_SR
WHERE DAE_CHT_TERM in (2094,2104,2114,2124)

),

FINAL_JOIN AS (

SELECT T2.DAE_CHT_TERM AS COHORT, T1.*
FROM        GRADES T1
INNER JOIN  COHORT T2 ON T1.EMPLID = T2.DAE_EMPLID

)


SELECT *
FROM FINAL_JOIN
